name: bagh_mama
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider:
  font_awesome_flutter:
  shared_preferences:
  flutter_easyloading:
  carousel_pro:
  fab_circular_menu:
  flutter_rating_bar:
  flutter_animated_dialog:
  vertical_barchart:
  pie_chart:
  expandable_text:
  cached_network_image:
  image_picker:
  dotted_decoration:
  url_launcher:
  animated_bottom_navigation_bar:
  circular_reveal_animation:
  auto_size_text:
  http:
  connectivity:
  flutter_spinkit:
  sqflite:
  path_provider:
  flutter_html:

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bm_head.png
    - assets/logo.png
  #Product Image
    - assets/product_image/cycle.jpg
    - assets/product_image/shoes.jpg
    - assets/product_image/product.jpg
  #Payment Image
    - assets/payment_image/bkash.png
    - assets/payment_image/cod.png
    - assets/payment_image/nagad.png
    - assets/payment_image/rocket.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

